### ISSUE TITLE
FE: ProfileEdit View - Benachrichtigungen implementieren

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#101]
- mit Hilfe von Flos globalem Nachrichtenmanager

**Comment by stefanowb** [comment]
- ProfileEdit View zeigt nun beim laden der Benutzerdaten und beim Speichern dieser alle möglichen Meldungen vom Backend an und lokalisiert diese

**Comment by Geopras** [comment]
fertsch
