### ISSUE TITLE
FE: Lokalisierung der Views, wenn Sprache im System geändert wird.

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#103]
Momentan werden Views erst durch neues Laden neu lokalisiert, nachdem die Systemsprache geändert wurde.

**Comment by stefanowb** [comment]
Eine View muss sich nun für folgendes Event Subscriben:

```
    var evLocalizeView = {
        topic: 'localizeView/profileEdit',
        cbFunction: localizeView
    };

    ideaWatcher.core.MessageBroker.subscribe(evLocalizeView);
```

und dabei ihre localizeView Methode aufrufen. Der Name der View hinter localizeView/ muss dabei genauso lauten, wie beim Subscriben von switchView. Den Rest erledigt der Localizer.

**Comment by Geopras** [comment]
fertsch
