### ISSUE TITLE
Lokalisierung von Registrierung, Login und Ideenlisten

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#104]
Die Ideenlisten sollen neu lokalisiert werden, nachdem die Systemsprache geändert wurde.

**Comment by stoe027** [comment]
Lokalisierung von Login und Registrierung passen.
Menü ist lokalisiert.
CategoryList bekommt den Text des Menüpunkts, der sie aufruft (ist also schon lokalisiert) --> TESTEN ob das wirklich beim spontanen Umstellen der Sprache funktioniert.

**Comment by Geopras** [comment]
Registrierung und Login Localization erledigt..
Ideenlisten werden in separatem Task mit localized
