### ISSUE TITLE
FE: Menübar Dropdownliste ändern (wenn angemeldet)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#108]
Localization mit beachten

**Comment by stoe027** [comment]
und Navigation beachten, oder als extra Aufgabe anlegen (also die neuen Menüpunkte sollen auch zu den richtigen Seiten führen)

**Comment by Geopras** [comment]
Ich kralle mir jetzt die Aufgabe, weil ich das MainMenu an meine Ideenlisten-Navigation anpasse und dabei auch die Logik verändern muss...

**Comment by Geopras** [comment]
Dropdown wechselt jetzt, sobald man erfolgreich angemeldet ist bzw. wenn man sich auslogged
