### ISSUE TITLE
BE: Automatischer Prozess für Idee-Ranking-Algorithmus

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#111]
Mit Hilfe eines automatisch laufenden Hintergrundprozesses (Thread) soll nach einem bestimmten Zeitintervall zu jeder Idee der jeweilige Rang für Hot, Fresh, Trending berechnet und gespeichert werden (auch sofort in der Datenbank)
-> Anfrage an DataManager für Roland vorgeben:
 im Interface "IIdeaController" eine entsprechende Methodendefinition anlegen

**Comment by stefanowb** [comment]
- Algorithmus ist fertig
  => was fehlt:
- Daten aus Backend holen
- automatisches Ausführen des Algorithmus in bestimmten Abständen

**Comment by stefanowb** [comment]
automatischer Prozess läuft im IdeaManager:
https://github.com/Geopras/IdeaWatcher/wiki/IdeaManager

es fehlt nur noch das Holen der Daten aus dem DataManager...
