### ISSUE TITLE
FE: IdeaDetails-View - Idee-Buttons anlegen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#115]
wenn User eingeloggt:
alle Ideenlisten (außer MyIdeas)
- Button: Like / not like -> über jeweils ein eigenes Icon
-> Like: Glühbirne an, not Like: aus
- Button: Follow / not follow (auch 2 Icons)
-> Stern grell ausgefüllt, nicht ausgefüllt

-> in die function renderItemList in der View ideaList-view

-> abhängig von Aufgabe Geopras/IdeaWatcher#105 

- Buttons mit data-attribute versehen -> objectId der Idee

**Comment by Geopras** [comment]
gehört zur View IdeaDetails

**Comment by stoe027** [comment]
Buttons existieren, wechseln das Bild auf Klick (wenn der Nutzer angemeldet ist)
sie erhalten automatisch das data-attribute: data-idea-id mit der passenden ideaId
