### ISSUE TITLE
BE: Workflow für Klick auf Like, Follow

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#117]

**Comment by stoe027** [comment]
- Like: Anzahl likes erhöhen und currentUser zu den "Likern" hinzufügen --> neue LIke Anzahl als Antwort ans Frontend
- Unlike: Anzahl likes verringern und currentUser aus "Likern" entfernen --> neue Like Anzahl als Antwort ans Backend
- Follow: Anzahl follower erhöhen und currentUser zu den "Followern" hinzufügen --> neue Follower Anzahl als Antwort ans Frontend
- Unfollow: Anzahl follower verringern und currentUser aus "Followern" entfernen --> neue Follower Anzahl als Antwort ans Backend

**Comment by Bassbiene** [comment]
theoretisch fertig, kann aber gerade nicht getestet werden, weil Backend bisher noch keine Idee zurückgeben kann.
