### ISSUE TITLE
DM: Creator-Objekt anlegen und in Idee speichern

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#125]
Bitte Creator-Objekt anlegen, der als eigenes Dokument in der MongoDB unter Idea.creator gespeichert wird.
Ein Interface und eine Klasse im Ordner dataManager/pojos wurden angelegt und muss noch ausimplementiert werden.

Beim Anlegen der Datenbank und beim Hinzufügen einer Idee (addIdea) muss ein neues Creator-Objekt aus dem zugehörigen User instanziiert werden und im Idea-Objekt gespeichert werden

**Comment by cs14rk1** [comment]
Warum soll eine weitere Collection in der MongoDB abgelegt werden? Halte ich für unnötig und überflüssig.

**Comment by cs14rk1** [comment]
erldeigt
