### ISSUE TITLE
FE: MyIdeas + FollowedIdeas Views + Logik

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#126]
MyIdeas-View:
Edit-Button -> führt zur CreateIdea-View mit vorausgefüllten Feldern

Delete-Button

**Comment by Geopras** [comment]
Buttons wurden angelegt und funktionieren wie in Task #95 beschrieben

Es werden die nötigen Requests versendet und mit Response-Callbackfunktionen auf den Erfolg reagiert bzw. der Misserfolg lokalized in einer Notification angezeigt
