### ISSUE TITLE
DM: Testdatensätze in DB angelegt und im Backend verwendet

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#13]

**Comment by Geopras** [comment]
- Datensätze zum Testen anlegen
- Abrufen und Speichern von Daten möglich
- keine feste Datenstruktur vorhanden (eigene Userstory)

**Comment by cs14rk1** [comment]
Testdatensätze mit MongoDB (Java)Driver als hierarchisches Dokument angelegt und ausgegeben in einer main- Methode
