### ISSUE TITLE
FE: IdeaDetails-View Edit-Button einbauen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#135]
Wenn ein Nutzer seine Ideen-Details sieht, soll er sie mit einem Button sofort bearbeiten dürfen

Dazu kommt von der MyIdeas-View ein Flag, dass es sich bei der Idee um eine eigene handelt und wenn der Nutzer auf den Edit-Button klickt wechselt die View auf CreateIdea-View mit den vorausgefüllten Feldern (genauso wie es schon von der MyIdeas-View passiert)

**Comment by stoe027** [comment]
Button ist in html da, wird in javascript gesetzt, wenn das flag true ist.

Noch zu tun:
- clickHandlermethode implementieren
