### ISSUE TITLE
FE: IdeaCreation-View: Anzeige Status nach Speichern neuer / editierter Idee

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#143]
Am besten ein Image für das Ergebnis des Speicherns (grünes Häkchen für Erfolg, rotes Kreuz Misserfolg)  gleich direkt neben dem Speichern-Button

**Comment by stefanowb** [comment]
Warum denn mit nem Image? Wir haben doch unseren schicken global Notifyer
=> siehe Speichern bei der ProfilEditView

**Comment by LoxGITLox** [comment]
wurde mit der GlobalNotification implementiert
