### ISSUE TITLE
BE: gelöschte Idee muss auch bei alles follwern aus den followedIdeas gelöscht werden

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#152]
- ansonsten kann ein solcher follower garnicht mehr auf followedIdeas zugreifen

**Comment by cs14rk1** [comment]
weiss nicht ob ich das hinbekomme, da wir nur die IDs in der followListe speichern. Für das ähnliche Problem mit isMailPublic, hatte ich dort das Problem mit deren Auswertung

**Comment by cs14rk1** [comment]
erledigt
