### ISSUE TITLE
BE, FE: wenn user keine Idee erstellt hat kann die createdIdeas Liste nicht angezeigt werden

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#153]
- bzw. wenn ein user seine einzige erstellte Idee löscht

**Comment by Geopras** [comment]
habs gefixt...

Jetzt wird immer die IdeaList-View angezeigt, auch wenn keine Ideen vorhanden sind...
es wird dazu eine Info-Notification angezeigt, dass keine Ideen vorhanden sind, die angezeigt werden könnten
