### ISSUE TITLE
FE: Login Maske wird nach erfolgreichem Login nicht geleert

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#157]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_28_SL

Testfall T0030 b)
anmelden, abmelden, erneut anmelden => Login Maske wurde nicht geleert => jemand anderes könnte sich an dem Rechner Zugriff zu dem Login des Users verschaffen

**Comment by LoxGITLox** [comment]
gefixt, clear View Methode implementiert
