### ISSUE TITLE
FE: Kommentar verschluckt Zeilenumbrüche (nice-to-have)

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#158]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_28_SL

T0110 b)
Idee kommentiert: Wenn man in einem Kommentar Zeilenumbrüche erzeugt, dann werden diese bei der Darstellung ignoriert. Der Text wird hintereinander ausgegeben.
nice-to-have: 	Kommentare wie eingegeben darstellen.

**Comment by stoe027** [comment]
hab den Zeilenumbruch gleich bei der IdeaDetailsView mit eingebaut.
