### ISSUE TITLE
FE: IdeaDetails-View: nicht angemeldeter User - bei Hover über like/follow Icon wird Maus zum Finger

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#160]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_28_SL

T0090 a)
nicht angemeldet: Bewertung ist nicht möglich aber bei Hover über Glübirne wird Maus zum Finger
T0100 a)
nicht angemeldet: Folgen ist nicht möglich aber bei Hover über Stern wird Maus zum Finger

**Comment by stoe027** [comment]
behoben.

**Comment by stoe027** [comment]
leider bleibt der Finger, wenn man sich mal angemeldet hatte und wieder abmeldet --> muss ich noch fixen.

**Comment by stoe027** [comment]
so, jetzt sollte es klappen.
