### ISSUE TITLE
FE: Hot-Listen laden beim Scrollen unendlich die letzten Einträge nach

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#164]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_28_SL/_edit

T0010 d)
egal, angemeldet oder abgemeldet - Nachladen von Ideen beim scrollen in funktioniert in Fresh,Trending - und dort auch bei den Kategorien. Es werden immer 10 Ideen nachgeladen, bis das Ender der Liste erreicht ist. Aber es funktioniert nicht in HOT! wenn man die Liste bis ans Ende scrollt, werden immer die letzte oder die letzten beiden Ideen nachgeladen - bis ins unendliche. Gilt auch für die Hot-Kategorien.

**Comment by Geopras** [comment]
Ist gefixt!

**Comment by Bassbiene** [comment]
Ideeliste scrollt nicht mehr ewig, aber es werden noch Ideen doppelt geladen :-(
