### ISSUE TITLE
Kategorienliste ist von myIdeas und followedIdeas nicht erreichbar

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#168]
Ergebnis leere Seite, Fehlermeldung in Browserkonsole:
Warnung: Für diese Nachricht gibt es keine Empfänger: switchView/undefined

**Comment by Geopras** [comment]
Wurde gefixt: Wenn ich auf Meine Ideen oder Meine verfolgten Ideen bin und auf eine Kategorie klicke, wechselt die View auf die Hot-Seite dieser Kategorie
