### ISSUE TITLE
Pflichtenheft am 4.11. 12 Uhr abgeben

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#17]
Das Pflichtenheft soll Abgabe bereit sein, da es am 4.11. beim Heller sein muss.

Pflichtenheft: Fr., 2016-11-04, 12:00 Uhr
- wie konkret soll es umgesetzt werden
- erste Gedanken zur Architektur, Hardware, Software-Anforderungen
- funktionale Anforderungen
- nichtfunktionale Anforderungen => skalierbarkeit, robostheit, ergonomie
  (Muster: example technical specification)
- Änderungen an Pflichtenheft jederzeit möglich => in Abschlussdoku darauf hinweisen

**Comment by Geopras** [comment]
Pflichtenheft: Fr., 2016-11-04, 12:00 Uhr
- wie konkret soll es umgesetzt werden
- erste Gedanken zur Architektur, Hardware, Software-Anforderungen
- funktionale Anforderungen
- nichtfunktionale Anforderungen => skalierbarkeit, robostheit, ergonomie
(Muster: example technical specification)
- Änderungen an Pflichtenheft jederzeit möglich => in Abschlussdoku darauf hinweisen

**Comment by stoe027** [comment]
Kurzübersicht dazu, was im Pflichtenheft laut Balzert enthalten sein muss (Herr Heller hatte Balzert meist auf der Literaturliste, zudem ähnelt der Aufbau dem bereits fertiger Pflichthefte der CS13)
https://www.unibw.de/rz/dokumente/getFILE?fid=993929

Beispiele Produktdaten und Funktionen:
http://hm.hgesser.de/ig-ws2008/folien/Pflichtenheft.pdf

**Comment by stoe027** [comment]
FRAGEN:
- Wie viele Ideen wollen wir bei Hot, Fresh, Trending jeweils anzeigen?
- Wie wird Trending berechnet (momentan steht im Pflichtenheft, dass der Algorithmus noch definiert werden muss).
- Richtet sich die Auswahl der Ideen für Fresh nach dem Anlage- oder dem Veröffentlichungsdatum (hat eventuell auch Einfluss auf die Datenhaltung, welches Datum speichern wir)?
- Was kann der Administrator, was andere angemeldete Nutzer nicht können? (gibts die Administratorrolle überhaupt?)
- Was tun unsere Kategorien im Prototyp? Vorschlag: Wir haben eine Liste hinterlegt, können daraus beim Anlegen von Ideen wählen, der Klick auf einzelne Kategorien im Menü hat keine Funktion.

Produktleistungen: Ladezeiten, Anzahl gleichzeitiger Nutzer, maximale Anzahl der Ideen, maximale Anzahl der Benutzer, Ausfallzeit

Qualitätsanforderungen: müssen wir zusammen definieren.

**Comment by Bassbiene** [comment]
![qualitaetsanforderungen.png](https://zube.io/files/Geopras/4976ff1d593d174f1d5e3687b2aa1a0c.png)

**Comment by stoe027** [comment]
so ihr lieben... bitte schaut euch das Heft mal an... schickt mir eure Korrekturen, ich arbeite sie dann ein.
Da liegt es:
https://github.com/Geopras/IdeaWatcher/blob/master/Doku/Dokumente/Pflichtenheft/Pflichtenheft.pdf

**Comment by stefanowb** [comment]
- hab es mal durchgelesen und meine Kommentare in ner extra PDF hochgeladen 
- ich find es sieht soweit schonmal ganz gut aus :)

**Comment by Geopras** [comment]
- Abbildung Komponentendiagramm zur Systemarchitektur einfügen

**Comment by stoe027** [comment]
Kapitel Architektur ist hinzugefügt.

**Comment by stoe027** [comment]
Habe das Pflichtenheft soeben an Herrn Heller verschickt.
Abgenickt von Stefan.
