### ISSUE TITLE
Bug: Nachladen von Ideen in Listen

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#170]
geht in firefox gar nicht, keine Fehlermeldung, weder in Browserkonsole noch im Backend.

**Comment by LoxGITLox** [comment]
Das Problem ist, dass Firefox document.documentElement.scrollTop nicht kennt und daher immer den den Wert 0 annimmt, daher wird das holen von neuen Ideen nicht angestoßen, die ganze endless Scroller Geschichte ist grundsätzlich relativ komplex, das was wir hier machen ist Performance-technisch grenzwertig, aber für den Moment sicherlich verschmerzbar ;-)
