### ISSUE TITLE
Bug: EditIdea - Logik in IdeaList und IdeaDetails

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#172]
Nutzer1 erstellt und veröffentlicht eine Idee. --> Abmelden, Anmelden als Nutzer 2
Nutzer 2 bewertet sie. --> Abmelden, Anmelden als Nutzer 1
--> Idee sollte nicht mehr Änderbar sein --> ist sie aber.

Problem in Chrome und Firefox

**Comment by Geopras** [comment]
Jetzt kann die eigene Idee nicht mehr bearbeitet werden, wenn zuvor bereits jemand sie geliked hat.
Es wird dann eine WARNING-Notification angezeigt, dass es nicht möglich ist, die Idee zu bearbeiten, da sie bereits geliked wurde (mit Localization)

**Comment by stoe027** [comment]
Firefox: erstelle Idee als user1, bewerte sie als user0, melde mich wieder als user1 an.
Navigiere neue Ideen --> öffne meine Idee in ideaDetails, edit --> speichern... geht.

**Comment by Geopras** [comment]
Wurde jetzt auch für IdeaDetails-View übernommen, sodass es in beiden Views jetzt geht
