### ISSUE TITLE
Bug: Idee veröffentlichen ohne zuvor zu speichern

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#174]
![Bildschirmfoto vom 2016-11-29 14-51-31.png](https://zube.io/files/Geopras/3a45f2948fdc50c340f8a1f6265178e0.png)
Problem im SaveEditPublishWorkflow. IdeaId wurde nie gesetzt, falls Idee vorm publishen nicht gespeichert wird, soll hier aber abgefragt werden.

**Comment by Geopras** [comment]
wurde gefixt
