### ISSUE TITLE
FE: Farbmarkierung Main-Menu wechselt nicht zu Hot, bei Sprung von myIdeas => Kategorie

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#179]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_29_SL-Chrome/_edit

T0010 c)
anmelden => Trending-Ideas aufrufen => Profil-Dropdown => MyIdeas => Kategorie Dropdwon => Kategorie wählen => Anzeige = Hot Ideas von Kategorie XY, aber Trending ist oben blau markiert

**Comment by stoe027** [comment]
bei mir im Chrome geht das.

**Comment by Geopras** [comment]
bei mir gehts auch
