### ISSUE TITLE
FE: Hot-Liste läd am Ende einen Ideen-Block doppelt

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#180]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_29_SL-Chrome

T0010 d)
Hot Liste läd ganz am Ende (ewig lange scrollen) einen Block mit 5 aufeinanderfolgenden Ideen 2 mal hintereinander. Danach folgen dann noch 2 einzelne Ideen. Alle anderen Listen funktionieren

**Comment by Geopras** [comment]
Wurde gefixt
Problem war noch eine fehlerhafte Logik bei der Filterung der Ideenliste im IdeaManager
Wurde so umgebaut, dass vor der Filterung jetzt alle veröffentlichten Ideen aus der DB geholt werden (abhängig von Kategorie) und die dann dem Filterbereich entsprechend gefiltert werden
