### ISSUE TITLE
FE: Maus wird noch zum Pointer, in IdeaDetails bei Like. Follow von eigener Idee (nice-to-have)

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#184]
https://github.com/Geopras/IdeaWatcher/wiki/Testprotokoll_2016_11_29_SL-Chrome/_edit

=> T090 c)
Ich kann eigene Idee nicht liken (korrekt) => Maus wird noch zum Pointer, obwohl Bewertung nicht möglich ist

**Comment by stoe027** [comment]
scheinbar doch schon behoben.
