### ISSUE TITLE
FE: Veröffentlichen Button editiert letzte Idee beim Erstellen einer neuen

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#192]
- Veröffentlichen-Button verändert immer die Idee, bei der man als letztes auf Edit geklickt hat - auch wenn man gerade eine neue Idee erstellt.

Ich hatte eine Idee als ein bestimmter User editiert (also eine vorhandene auf englisch übersetzt).
Dann hab ich mich abgemeldet und als anderer Benutzer wieder angemeldet. Mit dem hab ich ne neue Idee erstellt. => er hat aber keine neue Idee erstellt, sondern die zuvor bearbeitete verändert.

**Comment by Geopras** [comment]
wurde gefixt und im dev-Branch gepusht
