### ISSUE TITLE
Privatrechner im Internet verfügbar machen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#21]
Test: Teammitglied testet Verbindung

**Comment by cs14rk1** [comment]
Webserver aufsetzen und lokal zu erreichen war problemlos. Allerdings war es nicht möglich von aus außen auf den Server zu zu greiffen. Trotz Konfiguration der Weiterleitung auf dem Router  für Port 80. Nach stundenlanger Recherche habe ich es aufgegeben.
Entweder zu blöde oder Vodafon(Kabel Deutschland) macht mir einen Strich durch die Rechnung.
