### ISSUE TITLE
FE: Datenstruktur Idee-Objekt + Testdaten

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#25]
- Datenstruktur eines Ideen-Objekts
- Testdaten für Ideen in JSON-Datei anlegen
- zusammen mit Localization
- in eigenen Javascript-Objekten (Model im Frontend)
- Datenstrukturen an Roland weiterleiten

Testdatensätze für MongoDB

**Comment by Geopras** [comment]
- zusammen mit Localization
- in eigenen Javascript-Objekten (Model im Frontend)

**Comment by stefanowb** [comment]
- JSON Dateien für ideen, benutzer, logindaten und listen im Model angelegt
  (inklusive Testdaten)

**Comment by stefanowb** [comment]
- country geändert zu language
- language nun auch bei Idee
- Passwort-Hash verschoben zu User
- login.json ist obsolet => gelöscht

**Comment by Geopras** [comment]
neue Aufgabe in Sprint 6
