### ISSUE TITLE
FE: Datenstruktur User + Testdaten

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#26]
zusammen mit Localization erledigen
- in eigenen Javascript-Objekten (Model im Frontend)
- Datenstrukturen an Roland weiterleiten

Vollständige Testdatensätze anlegen, die in MongoDB importiert werden können

**Comment by Geopras** [comment]
zusammen mit Localization
- in eigenen Javascript-Objekten (Model im Frontend)

**Comment by stefanowb** [comment]
- JSON Dateien für ideen, benutzer, logindaten und listen im Model angelegt
  (inklusive Testdaten)

**Comment by stefanowb** [comment]
- country geändert zu language
- language nun auch bei Idee
- Passwort-Hash verschoben zu User
- login.json ist obsolet => gelöscht

**Comment by Geopras** [comment]
testUser.json angelegt mit einem TestUser für Login vorhanden
