### ISSUE TITLE
FE: Listenansicht der Testdaten (Ideen)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#27]
- CSS für Datenanzeige
- JavaScript -> HTML generisch aus Testdaten erzeugen
- Daten kommen vom Controller, der ein Test-JSON-Objekt über eine Testschnittstelle bereitstellt

**Comment by stoe027** [comment]
WebsocketConnector wandelt JSON-Objekt in JavascriptObjekt um.
Testdaten (JavascriptObjekt) liegen nicht im Controller, sondern in der Initialisierungsmethode, Flo sagt das passt so.

**Comment by LoxGITLox** [comment]
anzeige wird korrekt generiert, Details bezüglich den Übergabedaten müssen in späterem Sprint geklärt werden
