### ISSUE TITLE
FE: Profil-View

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#30]
- HTML + CSS der Profilansichtsseite

**Comment by stefanowb** [comment]
- Ist erstmal zum Testen in die index.html eingetragen - muss dann noch verschoben werden, wenn die Navigation funktioniert
- Ich habe das Layout im Dokument erst einmal mit einer Tabelle gelöst. Ich vermute, das macht man heutzutage nicht mehr so, habe aber auf die Schnelle keine Anleitung gefunden, wie man es denn richtig macht :-P 
- CSS für Formularfelder und Buttons und so habe ich in die globalStyles.less gepackt, da sie ja überall auf der Seite einheitlich aussehen sollen. Spezielle Ausrichtungssachen sind in der v-profileView.less

**Comment by LoxGITLox** [comment]
- HTML:
  - die Form passt, labels für Accessibility verwendet, sehr gut!
- CSS
  - globale Selektoren für input[type=text], input[type=email], select sollten meiner Meinung nach keine Angaben für _width_ und _display_ beinhalten, da jeder CSS Autor selbst über diese eigenschaften entscheiden sollte.
  - !important sollte in unseren stylesheets wenn möglich vermieden werden, da somit die CSS-Selektor hirachie untergraben wird. Zum Thema Rangordung von Selektoren:
    http://www.standardista.com/css3/css-specificity/

**Comment by stefanowb** [comment]
Profil-View angepasst:
- verschoben nach profileEditView
- CSS globalStyle enthält nun keine Positionen und Größen mehr => in die less Dateien der einzelnen Views v-profileEditView.less und v-signupView.less integriert
- !important-Attribute wurden entfernt
- Positionierung wird nun mit "position: relative" und "position: absolute" geregelt anstatt mit der Tabelle
  => damit das funktioniert musste der z-index des fixen header-menüs hochgesetz werden

**Comment by LoxGITLox** [comment]
passt
