### ISSUE TITLE
Doku MessageBroker

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#31]
- Meeting mit Flo zum von ihm implementierten MB-System
- Doku im Wiki dazu anlegen

**Comment by stoe027** [comment]
Der Eintrag ist hier:
https://github.com/Geopras/IdeaWatcher/wiki/MessageBroker

**Comment by LoxGITLox** [comment]
Formatierungen vorgenommen, einen Paragraphen entfernt der etwas Verwirrend war.
Ansonsten passt das gut, schön beschrieben.
