### ISSUE TITLE
Doku: UML Messagebroker

### ISSUE THREAD

**Issue by stefanowb** [Geopras/IdeaWatcher#34]
- dokumentieren der Funktionsweise des Messagebrokers in UML für das Pflichtenheft und die Präsie
- eventuell Umsetzung mit Kommunikationsdiagramm

**Comment by stefanowb** [comment]
Ergebnis: https://raw.githubusercontent.com/Geopras/IdeaWatcher/dev/Doku/Bilder/doku%20uml%20cd%20messagebroker%20login.jpg

Bouml-Projekt ist unter doku/uml eingecheckt
- Funktionsweise ist durch Flo abgesegnet
- könnte jemand die UML-Methodik checken (bin mir etwas unsicher was die Nummerierung betrifft. Ich ging jetzt davon aus, dass ein wenn eine Methode wieder eine Methode aufruft, dass diese dann einen Unternummerierungspunkt erhält)

**Comment by stoe027** [comment]
UML-Methodik sieht auch gut aus.
