### ISSUE TITLE
FE: CSS in less überführen

### ISSUE THREAD

**Issue by LoxGITLox** [Geopras/IdeaWatcher#37]

**Comment by LoxGITLox** [comment]
**Datei(en)**
alle neuen Dateien unter less

**Aufgaben ausgeführt**
-> überführung von css in less abgeschlossen, css Datei gelöscht

**Comment by stefanowb** [comment]
- Ist alles im less, hab ich für meine Profil-View auch schon fleißig verwendet. Aufbau ist gut nachvollziehbar.
- Ich schlage aber vor, für Farben konsequent Variablen zu verwenden, damit man einen einheitlichen Style gewährleisten kann.
