### ISSUE TITLE
Localization-Workflow ausarbeiten

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#40]
- JavaScript-Objekte für Mapping Deutsch-Englisch
- in HTML-Datei Platzhalter für Mapping-Objekt-Eigenschaften definieren (z.b. xxxUsername)
- in profile-view umsetzen

**Comment by stefanowb** [comment]
- unter controller gibt es nun eine Datei "lacalization.js": dort werden die Übersetzungen im JSON-Format definiert
- in Zukunft können die JSON Dateien auch im Backend vorgehalten und über den WebSocket abgerufen werden
- im Footer wird nun nach Aufbau der WebSocket-Verbindung die Methode "localizeViews" aufgerufen (mit dem Parameter de_DE)
- die Methode kann dann später über das Sprachmenü aufgerufen werden
- innerhalb der Methode werden für jede View einzelne Localize-Methoden aufgerufen, in denen diese die Einzelnen HTML-Elemente lokalisieren

Workflow würde ich mir folgendermaßen denken:
- Elemente werden im HTML erstmal auf englisch angelegt und mit einer vernünftigen ID versehen
- falls die Lokalisierung aus irgendeinem Grund nicht greifen sollte, währen die Elemente noch englisch benannt und lesbar => also verwenden wir keine Platzhalter (xxxUsername) oder so
- die Lokalisierung startet immer mit deutsch und damit springen uns Elemente, die wir noch nicht lokalisiert haben sofort ins Auge

Falls jemand irgendwo innerhalb von javascript dynamischen Text erzeugt, dann sollte er auch da immer das "i18n" Objekt verwenden. Dazu müsste man es vielleicht irgendwie in ein Objekt wie den MessageBroker packen. Da bräuchte ich dann mal Hilfe von Flo, wie man das am besten aufbaut.

**Comment by Geopras** [comment]
Warum kein Platzhalter? Was wenn der Text (= Element) irre lang ist, soll dann in die Objekteigenschaft über diesen langen Text angesprochen werden? -> Sehr unpraktikabel meiner Meinung nach...genau dafür gibt es ja Platzhalter, die das Key-Value-Paar eindeutig kennzeichnen
-> ich würde das jedenfalls nicht so akzeptieren...andere Meinungen??

Und wieso Localize-Methoden ?? Meiner Meinung nach gibt es für Deutsch und Englisch jeweils ein Mapping-Objekt, in dem zum entsprechenden Key (=Platzhalter) der Text als Value steht. Dann muss nur noch dieses Objekt über den Key angesprochen werden und schon hat man den Text.

Die Frage ist, welches Format soll die Datei mit dem Mapping-Objekt haben, um in verschiedenen Programmiersprachen verfügbar zu sein? z.B. JSON? XML?

**Comment by Geopras** [comment]
Soweit gut
Nur noch:
- Auslagern der Javascript-Objekte in eigene JS-Dateien 
- pro View eine eigene localization-JS-Datei
  -> in neuem Task verlegt
