### ISSUE TITLE
Passwort hashen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#41]
- Passwort in Hash konvertieren und mit Liste abgleichen
- Rückgabewert: Erfolg / Misserfolg melden

**Comment by stoe027** [comment]
wir sollten "Salz" hinzufügen --> einmaliger String, der vor dem Hashen an das Passwort angehängt wird und dadurch das verwenden von "Rainbow Tables" verhindert. Salz wird als Klartext in der Datenbank gespeichert.
in Java zum Beispiel mit jBCrypt
Passwortlänge und Anforderungen: 
https://wiki.selfhtml.org/wiki/Grundlagen/Sicherheit/sichere_Passwortwahl#Aufbau_eines_.28relativ.29_sicheren_Passworts
- besteht aus Groß- und Kleinbuchstaben
- Ziffern
- Umlauten
- Sonderzeichen
- mindestens acht Zeichen lang sein. 
  http://www.heise.de/forum/heise-Security/News-Kommentare/l-f-11-Jaehrige-erwuerfelt-und-verkauft-starke-Passphrasen/Wie-ein-Pfaelzer-ein-sicheres-Passwort-waehlt/posting-23852712/show/

**Comment by stoe027** [comment]
Passwort wird im DataManager gehasht.
Zum Vergleich des Klartextpassworts mit dem gehashten Passwort steht dort ebenfalls eine Method bereit.

**Comment by Geopras** [comment]
Hab beide Passwordmethoden in einem Unit-Test überprüft und sie funktionieren einwandfrei.
Der UnitTest ist unter Backend/src/test/UserServiceTest zu finden.
