### ISSUE TITLE
FE: View Profil Logik

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#42]
- View-Logik implementieren (Validierung und an Backend verschicken)
- Fehlermeldung bei falscher Eingabe
- Datenstruktur festlegen
- Daten verschicken und empfangen (Testdaten)

**Comment by stefanowb** [comment]
ProfileEditView
Frontend:
- kann nun UserData senden und empfangen (Frontend-seitig)
  => registriert sich am Messagebroger für die zugehörigen Events
  => führt die entsprechende Logik aus

was fehlt:
- Backend-seitige Implementierung
- Anzeige von Response-Meldung aus Backend (Speichern erfolgreich / geänderter Username nicht mehr verfügbar etc... )

**Comment by Geopras** [comment]
Logik zur Anzeige des Profils wurde vollständig im Backend sowie im Frontend umgesetzt, sodass bei erfolgreichem Login die Profildaten zu sehen sind...
dies kann mit dem Testdatensatz "testLogin.json" mit dem User "test" (PW: "Test1234") getestet werden

**Comment by Geopras** [comment]
fertsch
