### ISSUE TITLE
FE: View Login (Muster)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#43]
Es soll eine Mustervorlage für die Entwicklung von Views erstellt werden, sodass auch die Verwendung des MessageBroker und der Navigation klarer wird
-> Doku mit Hinweisen im Wiki (im Bereich Frontend)

**Comment by LoxGITLox** [comment]
Grundfunktionalitäten wurden implementiert
- HTML/CSS 
- Einblenden / Ausblenden der View
- Erzeugung Austausch Objekt auf Basis der Eingabewerte
- Herstellen der Verbindung zum Backend
- Objekt an Backend schicken

Es gibt einen Testeintrag im Hauptmenü, der sich Login nennt, von da aus kommt man zu der neuen View.

**Comment by stoe027** [comment]
@LoxGITLox: wenn ich "Login" anklicke, komme ich auf eine leere Seite... :-( Was mach ich falsch?
![Login.png](https://zube.io/files/Geopras/f236747a4d0396de294df963ebf78440.png)

**Comment by LoxGITLox** [comment]
hey ho,
das ist ein Sicherheitsproblem, wenn du via F12 die Konsole öffnest kannst du dir die Fehlermeldung anzeigen lassen. Das Grundproblem ist, dass das HTML/JS von deinem Lokalen Filesystem heraus ausgeführt wird, und bei der Navigation wird die History API des Browsers angesprochen, der Erlaubt eine Navigation auf dem lokalen Filesystem aber nicht, daher wird der Aufruf zum anzeigen der neuen View blockiert. Das Problem lässt sich sozusagen nicht leicht lösen, die Dateien müssen von einem lokalen Webserver ausgeliefert werden... ich würd sagen wir schauen uns das morgen mal zusammen an und entscheiden dann wie wir mit dem Problem umgehen... (es gibt noch einen kleinen, hässlichen workaround, damit das auch auf dem Filsystem funktioniert, dafür muss ich aber die Navigation anpassen und dann siehtst du die korrekte URL in der Addresszeile nicht mehr, das würd ich nur ungern machen ;-) )
