### ISSUE TITLE
BE: Auswahlalgorithmen für Hot, Fresh, Trending

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#44]
verbal Algorithmen formulieren
(für Pflichtenheft)

**Comment by Stiefelriemenbill** [comment]
schaut mal bitte drüber ob das so geht:

https://github.com/Geopras/IdeaWatcher/wiki/Algorithmus-Hot-Fresh-Trending

**Comment by stoe027** [comment]
Ich hab "Fresh" so verstanden, dass die Liste unabhängig von den Likes ist und tatsächlich nur das Veröffentlichungsdatum berücksichtigt.
Anstatt Erstellungsdatum wäre das Datum der Veröffentlichung besser, da eine Idee schon lange existieren kann, bevor sie veröffentlicht wird.
Ansonsten klingts gut...

wegen des Wegfallens: wir zeigen 10 Ideen direkt an, weitere können nachgeladen werden.
Ich weiß nicht, ob Ideen wegfallen können... denke sie werden halt nur sehr sehr weit hinten angezeigt...

**Comment by stefanowb** [comment]
Der Algorithmus ist fertig und funktioniert so denke ich ganz gut. Wurde mit 90 Ideen mit Zufallszahlen getestet.

Auf folgender Wiki-Seite findet Ihr:
- Beschreibung
- Pseudocode
- LibreOffice Dokument zum Testen

https://github.com/Geopras/IdeaWatcher/wiki/Algorithmus-Hot-Fresh-Trending

**Comment by Geopras** [comment]
approved
