### ISSUE TITLE
Autoformat nach Code-Conventions einrichten

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#46]
nach den Code-Conventions von André in der eigenen IDE die automatische Formatierung anpassen:
https://github.com/Geopras/IdeaWatcher/wiki/Style-Guide

Bitte jeder einen Kommentar hinzufügen, wenn erfolgreich eingerichtet

**Comment by Geopras** [comment]
Hab meine Auto-Formatierung geprüft

**Comment by stefanowb** [comment]
IntelliJ passt in den Voreinstellungen schon - da ist garnichts zu tun

**Comment by stoe027** [comment]
endlich auf beiden Computern erledigt.

**Comment by Geopras** [comment]
Roland hats auch gemacht
