### ISSUE TITLE
FE: View - Neuanlage einer Idee (reine Ansicht)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#47]
Wenn ein Benutzer eine neue Idee eintragen und veröffentlichen will, soll dies über eine Eingabemaske erfolgen
- erstmal nur HTML und CSS

**Comment by Stiefelriemenbill** [comment]
done

**Comment by Geopras** [comment]
Localization fehlt

**Comment by Stiefelriemenbill** [comment]
localization hinzugefügt

**Comment by Geopras** [comment]
fertsch
