### ISSUE TITLE
FE: View - Registrierung eines neuen Benutzers (Ansicht)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#49]
Die Registrierung eines neuen Benutzers soll über eine Eingabemaske möglich werden
- nur Ansicht (keine Logik)

**Comment by stoe027** [comment]
Ansicht erstellt. Einrückung der Hauptseite sowie Breite der Textfelder bisher noch nicht für alle geklärt, habe ich daher vorerst ignoriert.

**Comment by LoxGITLox** [comment]
passt
