### ISSUE TITLE
BE: Workflow - Login

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#53]
Vom Frontend kommt ein Request-Objekt mit Logindaten, welche vom Backend validiert werden soll
- Anfrage an DataManager stellen:
  -> gib mir das Passwort zum Usernamen (aus Request)
- Antwort an Frontend senden, ob Login korrekt

**Comment by Geopras** [comment]
Es existiert bereits der LoginWorkflow und die Datenbankabfrage dazu. An sich funktioniert die Validierung (wurde schon getestet), jedoch muss der TokenManager überarbeitet werden, sodass ein Token einem User zugeordnet wird...
und auch im Frontend muss die Speicherung und das Anhängen eines Tokens an einen Request (außer beim Login bzw. Signup) vorgenommen werden (meines Erachtens im WebSocketConnector)
Ein Testdatensatz wurde auch angelegt unter /dataManager/testData/testLogin.json
dort kann der erste User verwendet mit:
BN: test
PW: Test1234

**Comment by Geopras** [comment]
Der komplette Login-Ablauf wurde implementiert, außer die Nachricht an den Benutzer, ob der Login erfolgreich oder nicht war.
Auch das Token-Management wurde im Backend (im TokenManager) und im Frontend (im WebSocketConnector) eingebaut, sodass bei erfolgreichem Login der User einen Token erhält, mit dem er weitere Requests abgeben darf...der TokenManager prüft bei einem neuen Request (außer Login bzw. Signup), ob der Token existiert. Außerdem wird der Token zusammen mit dem eindeutigen Usernamen in einer HashMap im TokenManager gespeichert, sodass anhand des Tokens die Userdaten im DataManager abgefragt werden können.

Es wurde der Login mit besagten Testdatensatz aus testLogin.json mit dem ersten User erfolgreich getestet. Dazu wird bisher nur in der Browser-Console das Ergebnis der Login-Anfrage angezeigt.
Es erfolgt sonst keine Aktion nach einem erfolgreichem Login. Hier müsste noch eine festgelegt werden! Welche View soll dann angezeigt werden?

**Comment by stefanowb** [comment]
getestet und funzt
