### ISSUE TITLE
BE: Workflow - Ideenliste - nach Hot filtern

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#55]
Nach Anfrage der Ideenliste vom Frontend soll WebApi die Liste aller Ideen vom DataManager erhalten
und nach dem Hot-Kriterium filtern
Die gefilterte Ideenliste soll zurückgegeben werden bzw. die Fehlermeldung

**Comment by stefanowb** [comment]
Backend: getIdeaList
=> fast fertig
=> was fehlt:
- Übergabe am Ende
  (wie sollen mehrere JSON-Objekte übergeben werden?)
- holen der Ideen vom DataManager
  (arbeitet momentan mit selbst erzeugten Testdaten)

**Comment by stefanowb** [comment]
Filter funktioniert und ist fertig.
Nur der IdeaManager muss noch seine Daten vom DataManager erhalten, aber das ist ein anderer Task...
