### ISSUE TITLE
BE: Workflow - Ideenliste - nach Fresh filtern

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#56]
Filteralgorithmus für Anzeige von Fresh Ideen umsetzen
- Ideenliste vom DataManager anfragen
- gefilterte Liste zurückgeben

**Comment by stefanowb** [comment]
Backend: getIdeaList
=> fast fertig
=> was fehlt:
- Übergabe am Ende
  (wie sollen mehrere JSON-Objekte übergeben werden?)
- holen der Ideen vom DataManager
  (arbeitet momentan mit selbst erzeugten Testdaten)

**Comment by stefanowb** [comment]
Filter funktioniert und ist fertig.
Nur der IdeaManager muss noch seine Daten vom DataManager erhalten, aber das ist ein anderer Task...
