### ISSUE TITLE
HTML-Gerüst anlegen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#6]
Single-Page-Application:
eine HTML5-Seite anlegen
- div-Container definieren

**Comment by LoxGITLox** [comment]
**Datei(en)** 
IdeaWatcher/Frontend/dev/view/index.html

**Aufgaben ausgeführt**
-> Datei index.html wurde angelegt
-> Container für Hauptmenü + alle bisher definierten Views angelegt
-> viewport meta Tag hinzugefügt um input delay für mobile Endgeräte zu verhindern
siehe : https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Tester**
-> bitte Namenskonventionen prüfen, wenn anders gewünscht, am Ende des Sprints klären, da Team Entscheidung
