### ISSUE TITLE
DM: für LoginWorkflow Schnittstellen anbieten

### ISSUE THREAD

**Issue by cs14rk1** [Geopras/IdeaWatcher#60]
Es soll für den LoginWorkflow eine API bereitgestellt werden, die folgende Abfragen ermöglicht:
- existsUser(String userName)  -> zur Prüfung, ob ein bestimmter User existiert
- getUser(String userName)   -> um ein komplettes User-JsonObjekt zu erhalten

**Comment by Geopras** [comment]
Methoden wurden angelegt
