### ISSUE TITLE
DM: Registrierung - Schnittstellen anbieten

### ISSUE THREAD

**Issue by cs14rk1** [Geopras/IdeaWatcher#61]
Es soll möglich sein, einen neuen User anzulegen.

Folgende Schnittstellen sollen dazu angeboten werden:
- existsUser(String userName)   -> die gleiche Schnittstelle wie für den LoginWorkflow
- addUser(User user)

Die Datenstruktur wurde in dieser JSON-Datei von Stefan festgelegt:
https://github.com/Geopras/IdeaWatcher/blob/master/Frontend/dev/model/user.json

**Comment by Geopras** [comment]
Die Methoden wurden angelegt, aber noch nicht getestet

**Comment by Geopras** [comment]
fertsch
