### ISSUE TITLE
Wiki-Doku: Einrichten des Apache Servers

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#65]
Es soll im Wiki dokumentiert werden, wie der Apache Server eingerichtet werden muss, damit die Webanwendung darüber läuft und somit auch die Navigation funktioniert (da die HTML-Seite nicht vom lokalen Filesystem ausgeführt wird sondern über die URL des Apache)

**Comment by Stiefelriemenbill** [comment]
Erster Draft:

https://github.com/Geopras/IdeaWatcher/wiki/Apache-Server

**Comment by Stiefelriemenbill** [comment]
done
