### ISSUE TITLE
Bugfix: Inhalte verschwinden hinter dem Menü

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#67]
Die Inhalte sollten unter dem Menü angezeigt werden

**Comment by stoe027** [comment]
André hats gefunden und jemand anders hats gefixt... war wohl eine fehlende Umbenennung

**Comment by stefanowb** [comment]
das war ich :-P

**Comment by stoe027** [comment]
guter Mann :-D
