### ISSUE TITLE
FE: Localization - Fehlernachrichten aus dem Backend

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#69]
Es soll eine Mapping-Javascript-Datei zur Anzeige von Fehlernachrichten aus dem Backend existieren.
Das Mapping-Objekt soll an die "localizer"-Komponente angehangen werden, so wie die localizer für die einzelnen Views.

Folgende Keys für Nachrichten gibt es bereits im Backend:

- "SLogin/getUser_error" -> Text de_DE: "Die Anmeldung ist bei der Datenbankabfrage des Benutzers fehlgeschlagen! Bitte wenden Sie sich an den WebApi-Administrator."
- "SLogin/password_not_valid" -> Text de_DE: "Die Anmeldung ist fehlgeschlagen, weil das Passwort ungültig ist."
- "SSignup/existsUser_error" -> Text de_DE: "Die Registrierung ist bei der Datenbankabfrage, ob der Benutzer bereits existiert, fehlgeschlagen! Bitte wenden Sie sich an den WebApi-Administrator."
- "SSignup/addUser_error" -> Text de_DE: "Die Registrierung ist bei der Datenbankoperation "Hinzufügen eines neuen Benutzers" fehlgeschlagen! Bitte wenden Sie sich an den WebApi-Administrator."
- "SSignup/username_already_exists" -> Text de_DE: "Die Registrierung ist nicht möglich, da der Benutzername bereits existiert."

**Comment by stoe027** [comment]
Pfad zur Mapping-Javascript-Datei: /IdeaWatcherProject/Frontend/dev/view/javascript/localization/errorMessage-localizer.js

**Comment by stoe027** [comment]
Entscheidung von geopras --> die Fehlermeldungen kommen doch in die localizer der Views...

**Comment by stoe027** [comment]
hab die Fehlermeldung in die localizer der Views eingetragen und den ErrorMessage-localizer gelöscht.

**Comment by Geopras** [comment]
Localization mit Fehlerausgabe wird von Flo mit erledigt
