### ISSUE TITLE
FE: Mockup Grundgerüst Hauptseite

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#7]
Hauptseite zeichnen

**Comment by stefanwebo** [comment]
Ich schlage folgende Lizenz vor:
BSD 3-clause Clear License

- Lizenz: http://choosealicense.com/licenses/bsd-3-clause-clear/
- Übersicht: http://choosealicense.com/appendix/

- Vorteile:
   => Veränderungen können unter einer neuen Lizenz veröffentlicht werden (wird gerne für Vorlagen von späteren proprietären Systemen verwendet)
   => ursprünglicher Part muss unter dieser Lizenz mit dem Copyright bleiben
   => das Projekt ist in irgendeiner Art davor geschützt, dass jemand anders es dann aufgreift, modifiziert und patentiert (wenn ich das richtig verstanden habe)

**Comment by stefanowb** [comment]
- das Mockup ist hier zu finden: https://github.com/Geopras/IdeaWatcher/wiki/Mockups

**Comment by stoe027** [comment]
getestet in Sprint Review am 19.10.
