### ISSUE TITLE
BE: Projekt anlegen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#8]
Projekt für Backend anlegen (Java)

**Comment by stoe027** [comment]
@LOX: hast du das nicht schon erledigt?

**Comment by LoxGITLox** [comment]
ich würde sagen, dass die Grundstruktur noch fehlt, ich habe nur geprüft, ob es möglich ist das Projekt unter Eclipse zu verwenden.

**Comment by LoxGITLox** [comment]
**Datei(en)**
IdeaWatcher/Backend/src/de/ideaWatcher/endpoint/WebSocketEndpoint.java
IdeaWatcher/Backend/src/de/ideaWatcher/lifeCycle/LifeCycle.java
IdeaWatcher/Backend/src/de/ideaWatcher/model/TestModel.java
IdeaWatcher/Backend/src/de/ideaWatcher/workflow/WorkflowTestClass.java

**Aufgaben ausgeführt**
-> Grundstruktur erzeugt, damit die Implementierung starten kann

**Tester**
-> bitte Namenskonventionen prüfen, wenn anders gewünscht, am Ende des Sprints klären, da Team Entscheidung

**Comment by lox** [comment]
??

**Comment by Bassbiene** [comment]
Dear Lox.
I am sorry about the confusion. I was trying to mention LoxGITLox, my colleague and didn't know that by shortening his name I would reach you ;)

**Comment by lox** [comment]
No problems!

**Comment by Geopras** [comment]
Grundstruktur WebAPI ist vom Team abgesegnet
