### ISSUE TITLE
MongoDB installieren und Daten importieren

### ISSUE THREAD

**Issue by stoe027** [Geopras/IdeaWatcher#85]
Anleitung zum Installieren von Roland ist im Wiki
Mongo Booster ausführen
neue Datenbank erstellen
- Import Collections

**Comment by stoe027** [comment]
erledigt (mit Hilfe)

**Comment by Geopras** [comment]
auch erledigt und schon damit erfolgreich getestet

**Comment by stefanowb** [comment]
auch erledigt

**Comment by LoxGITLox** [comment]
erledigt

**Comment by Stiefelriemenbill** [comment]
done
