### ISSUE TITLE
FE: Language-Switch Logik

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#89]

**Comment by stoe027** [comment]
System-Sprache wird geändert.
Icon wurde entsprechend angepasst (hat Englisch angezeigt, wenn wir auf Deutsch waren).
Wird die Profil-Edit-View aufgerufen und nach Sprachänderung neu geladen, wird die Sprachänderung korrekt angezeigt.

**Comment by Stiefelriemenbill** [comment]
icons englisch deutsch getauscht

**Comment by stefanowb** [comment]
- getestet und funktioniert
