### ISSUE TITLE
BE: Lokalen ApplicationServer einrichten

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#9]
Einrichten eines TomCat-Servers unter localhost

**Comment by stoe027** [comment]
im Wiki unter Backend 2 Seiten für die Einrichtung des Servers in Eclipse und IntelliJ erstellt. Bedingung ist ein vorhandenes Projekt in beiden IDEs.

JEDER von uns sollte bei sich lokal einen Tomcat einrichten. Wenn fertig, könnt ihr euch aus den Assignees nehmen.
Der letzte schiebt den Task auf "In Test" und weißt mir die Aufgabe wieder zu.

**Comment by Geopras** [comment]
Hab meinen lokalen Tomcat-Server ohne IDE in Ubuntu installiert
den Link zur Beschreibung der Installation habe ich in unser Wiki gepackt

**Comment by Stiefelriemenbill** [comment]
Tomcat-Server ist eingericht

Eine Bitte an den Rest: Rückmeldung geben damit der Task geschlossen werden kann.

**Comment by Geopras** [comment]
Flo, Stefan haben ihn eingerichtet

**Comment by LoxGITLox** [comment]
läuft

**Comment by Geopras** [comment]
bei Roland läufts auch
