### ISSUE TITLE
FE: Kategorien einpflegen

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#92]
im Frontend in Dropdown (Menüleiste) einfügen
und bei create new idea
max. 5 Einträge
Dropdown-Breite dynamisch (wegen untersch. Sprachen)

**Comment by stefanowb** [comment]
sind jetzt 7, ich hoffe ihr schlachtet mich nicht ;)

Business & Science
Computer & Electronics
Gadget
Home & Garden
Sports & Outdoor
Toys, Children & Pets
Other

---

Gewerbe & Wissenschaft
Computer & Elektronik
Gadget
Haushalt & Garten
Sport & Freizeit
Spielzeug & Haustier
Anderes

**Comment by stefanowb** [comment]
Okay @Stiefelriemenbill  - kannste jetzt einpflegen :)

**Comment by Stiefelriemenbill** [comment]
kategorien sind drin 
localisierung fehlt noch wird mit meinem Task menü mitgemacht bei dem auch noch die lokalisierung fehlt

**Comment by stefanowb** [comment]
- sind drin, getestet und ok
