### ISSUE TITLE
FE: Registrierung - Passwortrichtlinien

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#94]
Folgende Regeln sollen im Frontend über Javascript geprüft werden bei Passworteingabe in der Registrierungs-View:

besteht aus Groß- und Kleinbuchstaben
Ziffern
Umlauten
Sonderzeichen
mindestens acht Zeichen lang sein.

**Comment by stoe027** [comment]
habs jetzt nicht mit einer einzigen Regex sondern mit ner Schleife und mehreren Regex gelöst.
nebenbei gleich noch die Lokalisierung der Registrierungsview gemacht (fehlte noch).
Fehlermeldungen werden in Labels ausgegeben.
äöüß sind verbotene Zeichen... 
Passwort kann man erst wiederholen, wenn Passwort den Richtlinien entspricht.
Form kann man erst abschicken, wenn Passwörter übereinstimmen.

**Comment by Geopras** [comment]
von Flo abgenommen
