### ISSUE TITLE
FE: View - IdeaDetails (Ansicht)

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#96]

**Comment by stoe027** [comment]
Ansicht funktioniert mit Testdaten, die direkt im UIConnector angelegt sind.
noch zu tun:

- Kommentar muss nach erfolgreichem speichern wie andere gegebene Kommentare dargestellt werden

**Comment by Geopras** [comment]
Für Buttons gibt es eine extra Aufgabe

**Comment by Bassbiene** [comment]
- Methode nach Antwort des Backends implementieren (Anzahl der Likes und Follows muss neu gesetzt werden. --> theoretisch erledigt, aber grad nicht testbar.
- section "neuer Kommentar" nur angezeigt, wenn Nutzer eingeloggt ist

**Comment by stoe027** [comment]
tut sie :-D
