### ISSUE TITLE
DM: Weitere Schnittstellen im UserController

### ISSUE THREAD

**Issue by Geopras** [Geopras/IdeaWatcher#99]
Es müssen noch folgende Schnittstellenmethoden im UserController implementiert werden:
- existsEmail()
- deleteUser()
- changeUser()

**Comment by cs14rk1** [comment]
Was soll der user mit changeUser() ändern dürfen ? Haben wir das irgendwo festgelegt ?
Ich gehe mal davon aus, dass ein registrierter user nicht seine Angaben zu den Namen ( user, Vorname, Nachname ) ändern darf.

**Comment by Geopras** [comment]
gibt noch eine extra Aufgabe zu changeUser()

**Comment by cs14rk1** [comment]
changeUser/Idea geändert in updateUser/Idea

Methoden implementiert
